### ISSUE TITLE
Adding names

### ISSUE THREAD

**Issue by michaeldugan** [wwdc/2016#23]
How would I go about adding myself to this list?

**Comment by Schemetrical** [comment]
Click the edit button and make the changes. Then click submit pull request and I'll pull it.

**Comment by Schemetrical** [comment]
https://github.com/wwdc/2016/edit/master/README.md

**Comment by ezhes** [comment]
Aww man I wish I know about this before I made three pull requests trying to the commit correct. Nifty feature!

**Comment by Schemetrical** [comment]
@shusain93 haha :)

**Comment by kylespadaro-zz** [comment]
How long does it take to get commited? My name isn't on the list yet, but I edited and added my info. Do I have to wait for someone to accept it?

**Comment by cyhsutw** [comment]
@kylespadaro I think @Schemetrical will accept the pull request when he's available. It won't take much time 😄

**Comment by kylespadaro-zz** [comment]
@cyhsutw the message just came up now.

**Comment by Schemetrical** [comment]
Yup @kylespadaro I'm on the other side of the world 😛 
@michaeldugan you have to fix your PR. Just close the current one and make a new one with changes.
