### ISSUE TITLE
Could we add a column for the Apple technology which has been used?

### ISSUE THREAD

**Issue by termorrell** [wwdc/2016#60]
This year Apple asked us to build apps that demonstrated a creative use of Apple technologies. It would be useful to see which technologies everyone else managed to incorporate!

**Comment by Schemetrical** [comment]
I could but space wise I don't know where to put it. The table is pretty wide as it is. It will be pretty cool though, I'll think about it :)

**Comment by termorrell** [comment]
Cheers 👍

**Comment by hharanm** [comment]
That is an awesome idea!

**Comment by kylespadaro-zz** [comment]
Great idea!

**Comment by k3zi** [comment]
Maybe we could just add a folder called "Contestants" that holds separate markdown files for each user. Then create a link "More Info" on the main list to redirect users to the separate file. This way users can add more info and it would still be structured.

**Comment by Schemetrical** [comment]
@k3zi I think this is a great idea. I'll begin work on it, lmk if you want push access :)

**Comment by Schemetrical** [comment]
Actually, its probably easier if I combine social media with their name. I'll update with a new column and you'll see.

**Comment by k3zi** [comment]
@Schemetrical That was my second thought :)

**Comment by Schemetrical** [comment]
@k3zi do you mind editing it to match the first few rows? I'm quite busy so I won't be able to make all the changes. I gave you write access.

**Comment by k3zi** [comment]
@Schemetrical Sure!
